<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAspireHost>true</IsAspireHost>
    <UserSecretsId>b93741d1-bc19-4800-80c0-29bfb44c7daf</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Caligula.ApiService\Caligula.ApiService.csproj" />
    <ProjectReference Include="..\Caligula.Api\Caligula.Service.csproj" />
    <ProjectReference Include="..\Caligula.Web\Caligula.Web.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="8.2.2" />
  </ItemGroup>

</Project>
